[unstable]
# Enables the usage of the intrinsics inside compiler_builtins
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "arm64.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"